let treeData = {
  "id": "Movies",
  "index": 0,
  "level": 0,
  "seq": 0,
  "label": "Movies",
  "description": "",
  "categoryIndex": 0,
  "categoryLabel": "",
  "color": "#0088FF",
  "data": {},
  "visible": true,
  "children": [
    {
      "id": "Movies.Action",
      "index": 1,
      "level": 1,
      "seq": 0,
      "label": "Action",
      "description": "",
      "categoryIndex": 0,
      "categoryLabel": "",
      "color": "#0088FF",
      "data": {},
      "visible": true,
      "children": [
        {
          "id": "Movies.Action.Avatar ",
          "index": 2,
          "level": 2,
          "seq": 0,
          "label": "Avatar ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "760505847",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Jurassic World ",
          "index": 3,
          "level": 2,
          "seq": 1,
          "label": "Jurassic World ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "652177271",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.The Avengers ",
          "index": 4,
          "level": 2,
          "seq": 2,
          "label": "The Avengers ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "623279547",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.The Dark Knight ",
          "index": 5,
          "level": 2,
          "seq": 3,
          "label": "The Dark Knight ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "533316061",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Star Wars: Episode I - The Phantom Menace ",
          "index": 6,
          "level": 2,
          "seq": 4,
          "label": "Star Wars: Episode I - The Phantom Menace ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "474544677",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Star Wars: Episode IV - A New Hope ",
          "index": 7,
          "level": 2,
          "seq": 5,
          "label": "Star Wars: Episode IV - A New Hope ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "460935665",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Avengers: Age of Ultron ",
          "index": 8,
          "level": 2,
          "seq": 6,
          "label": "Avengers: Age of Ultron ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "458991599",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.The Dark Knight Rises ",
          "index": 9,
          "level": 2,
          "seq": 7,
          "label": "The Dark Knight Rises ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "448130642",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Pirates of the Caribbean: Dead Man's Chest ",
          "index": 10,
          "level": 2,
          "seq": 8,
          "label": "Pirates of the Caribbean: Dead Man's Chest ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "423032628",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Iron Man 3",
          "index": 11,
          "level": 2,
          "seq": 9,
          "label": "Iron Man 3",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "408992272",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Captain America: Civil War ",
          "index": 12,
          "level": 2,
          "seq": 10,
          "label": "Captain America: Civil War ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "407197282",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Spider-Man ",
          "index": 13,
          "level": 2,
          "seq": 11,
          "label": "Spider-Man ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "403706375",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Transformers: Revenge of the Fallen ",
          "index": 14,
          "level": 2,
          "seq": 12,
          "label": "Transformers: Revenge of the Fallen ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "402076689",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Star Wars: Episode III - Revenge of the Sith ",
          "index": 15,
          "level": 2,
          "seq": 13,
          "label": "Star Wars: Episode III - Revenge of the Sith ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "380262555",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.The Lord of the Rings: The Return of the King ",
          "index": 16,
          "level": 2,
          "seq": 14,
          "label": "The Lord of the Rings: The Return of the King ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "377019252",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Spider-Man 2",
          "index": 17,
          "level": 2,
          "seq": 15,
          "label": "Spider-Man 2",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "373377893",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Deadpool ",
          "index": 18,
          "level": 2,
          "seq": 16,
          "label": "Deadpool ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "363024263",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Transformers: Dark of the Moon ",
          "index": 19,
          "level": 2,
          "seq": 17,
          "label": "Transformers: Dark of the Moon ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "352358779",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.American Sniper ",
          "index": 20,
          "level": 2,
          "seq": 18,
          "label": "American Sniper ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "350123553",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Furious 7",
          "index": 21,
          "level": 2,
          "seq": 19,
          "label": "Furious 7",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "350034110",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.The Lord of the Rings: The Two Towers ",
          "index": 22,
          "level": 2,
          "seq": 20,
          "label": "The Lord of the Rings: The Two Towers ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "340478898",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Spider-Man 3",
          "index": 23,
          "level": 2,
          "seq": 21,
          "label": "Spider-Man 3",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "336530303",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Minions ",
          "index": 24,
          "level": 2,
          "seq": 22,
          "label": "Minions ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "336029560",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Guardians of the Galaxy ",
          "index": 25,
          "level": 2,
          "seq": 23,
          "label": "Guardians of the Galaxy ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "333130696",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Batman v Superman: Dawn of Justice ",
          "index": 26,
          "level": 2,
          "seq": 24,
          "label": "Batman v Superman: Dawn of Justice ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "330249062",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Transformers ",
          "index": 27,
          "level": 2,
          "seq": 25,
          "label": "Transformers ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "318759914",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Iron Man ",
          "index": 28,
          "level": 2,
          "seq": 26,
          "label": "Iron Man ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "318298180",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Indiana Jones and the Kingdom of the Crystal Skull ",
          "index": 29,
          "level": 2,
          "seq": 27,
          "label": "Indiana Jones and the Kingdom of the Crystal Skull ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "317011114",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.The Lord of the Rings: The Fellowship of the Ring ",
          "index": 30,
          "level": 2,
          "seq": 28,
          "label": "The Lord of the Rings: The Fellowship of the Ring ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "313837577",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Iron Man 2",
          "index": 31,
          "level": 2,
          "seq": 29,
          "label": "Iron Man 2",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "312057433",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Star Wars: Episode II - Attack of the Clones ",
          "index": 32,
          "level": 2,
          "seq": 30,
          "label": "Star Wars: Episode II - Attack of the Clones ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "310675583",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Pirates of the Caribbean: At World's End ",
          "index": 33,
          "level": 2,
          "seq": 31,
          "label": "Pirates of the Caribbean: At World's End ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "309404152",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Star Wars: Episode VI - Return of the Jedi ",
          "index": 34,
          "level": 2,
          "seq": 32,
          "label": "Star Wars: Episode VI - Return of the Jedi ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "309125409",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Independence Day ",
          "index": 35,
          "level": 2,
          "seq": 33,
          "label": "Independence Day ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "306124059",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Pirates of the Caribbean: The Curse of the Black Pearl ",
          "index": 36,
          "level": 2,
          "seq": 34,
          "label": "Pirates of the Caribbean: The Curse of the Black Pearl ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "305388685",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Skyfall ",
          "index": 37,
          "level": 2,
          "seq": 35,
          "label": "Skyfall ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "304360277",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Inception ",
          "index": 38,
          "level": 2,
          "seq": 36,
          "label": "Inception ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "292568851",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Man of Steel ",
          "index": 39,
          "level": 2,
          "seq": 37,
          "label": "Man of Steel ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "291021565",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Star Wars: Episode V - The Empire Strikes Back ",
          "index": 40,
          "level": 2,
          "seq": 38,
          "label": "Star Wars: Episode V - The Empire Strikes Back ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "290158751",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.The Matrix Reloaded ",
          "index": 41,
          "level": 2,
          "seq": 39,
          "label": "The Matrix Reloaded ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "281492479",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.The Amazing Spider-Man ",
          "index": 42,
          "level": 2,
          "seq": 40,
          "label": "The Amazing Spider-Man ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "262030663",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.The Incredibles ",
          "index": 43,
          "level": 2,
          "seq": 41,
          "label": "The Incredibles ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "261437578",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Captain America: The Winter Soldier ",
          "index": 44,
          "level": 2,
          "seq": 42,
          "label": "Captain America: The Winter Soldier ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "259746958",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.The Lego Movie ",
          "index": 45,
          "level": 2,
          "seq": 43,
          "label": "The Lego Movie ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "257756197",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Star Trek ",
          "index": 46,
          "level": 2,
          "seq": 44,
          "label": "Star Trek ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "257704099",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Batman ",
          "index": 47,
          "level": 2,
          "seq": 45,
          "label": "Batman ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "251188924",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Action.Night at the Museum ",
          "index": 48,
          "level": 2,
          "seq": 46,
          "label": "Night at the Museum ",
          "description": "",
          "categoryIndex": 1,
          "categoryLabel": "Action",
          "color": "#16B59B",
          "data": {},
          "value": "250863268",
          "visible": true,
          "children": []
        }
      ]
    },
    {
      "id": "Movies.Drama",
      "index": 49,
      "level": 1,
      "seq": 1,
      "label": "Drama",
      "description": "",
      "categoryIndex": 0,
      "categoryLabel": "",
      "color": "#0088FF",
      "data": {},
      "visible": true,
      "children": [
        {
          "id": "Movies.Drama.Titanic ",
          "index": 50,
          "level": 2,
          "seq": 0,
          "label": "Titanic ",
          "description": "",
          "categoryIndex": 2,
          "categoryLabel": "Drama",
          "color": "#6F3BD5",
          "data": {},
          "value": "658672302",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Drama.The Sixth Sense ",
          "index": 51,
          "level": 2,
          "seq": 1,
          "label": "The Sixth Sense ",
          "description": "",
          "categoryIndex": 2,
          "categoryLabel": "Drama",
          "color": "#6F3BD5",
          "data": {},
          "value": "293501675",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Drama.I Am Legend ",
          "index": 52,
          "level": 2,
          "seq": 2,
          "label": "I Am Legend ",
          "description": "",
          "categoryIndex": 2,
          "categoryLabel": "Drama",
          "color": "#6F3BD5",
          "data": {},
          "value": "256386216",
          "visible": true,
          "children": []
        }
      ]
    },
    {
      "id": "Movies.Adventure",
      "index": 53,
      "level": 1,
      "seq": 2,
      "label": "Adventure",
      "description": "",
      "categoryIndex": 0,
      "categoryLabel": "",
      "color": "#0088FF",
      "data": {},
      "visible": true,
      "children": [
        {
          "id": "Movies.Adventure.Shrek 2",
          "index": 54,
          "level": 2,
          "seq": 0,
          "label": "Shrek 2",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "436471036",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.The Hunger Games: Catching Fire ",
          "index": 55,
          "level": 2,
          "seq": 1,
          "label": "The Hunger Games: Catching Fire ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "424645577",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.The Lion King ",
          "index": 56,
          "level": 2,
          "seq": 2,
          "label": "The Lion King ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "422783777",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.Toy Story 3",
          "index": 57,
          "level": 2,
          "seq": 3,
          "label": "Toy Story 3",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "414984497",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.The Hunger Games ",
          "index": 58,
          "level": 2,
          "seq": 4,
          "label": "The Hunger Games ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "407999255",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.Frozen ",
          "index": 59,
          "level": 2,
          "seq": 5,
          "label": "Frozen ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "400736600",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.Finding Nemo ",
          "index": 60,
          "level": 2,
          "seq": 6,
          "label": "Finding Nemo ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "380838870",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.The Jungle Book ",
          "index": 61,
          "level": 2,
          "seq": 7,
          "label": "The Jungle Book ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "362645141",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.Jurassic Park ",
          "index": 62,
          "level": 2,
          "seq": 8,
          "label": "Jurassic Park ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "356784000",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.Inside Out ",
          "index": 63,
          "level": 2,
          "seq": 9,
          "label": "Inside Out ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "356454367",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.The Hunger Games: Mockingjay - Part 1",
          "index": 64,
          "level": 2,
          "seq": 10,
          "label": "The Hunger Games: Mockingjay - Part 1",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "337103873",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.Alice in Wonderland ",
          "index": 65,
          "level": 2,
          "seq": 11,
          "label": "Alice in Wonderland ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "334185206",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.Shrek the Third ",
          "index": 66,
          "level": 2,
          "seq": 12,
          "label": "Shrek the Third ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "320706665",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.Harry Potter and the Sorcerer's Stone ",
          "index": 67,
          "level": 2,
          "seq": 13,
          "label": "Harry Potter and the Sorcerer's Stone ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "317557891",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.The Hobbit: An Unexpected Journey ",
          "index": 68,
          "level": 2,
          "seq": 14,
          "label": "The Hobbit: An Unexpected Journey ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "303001229",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.Harry Potter and the Half-Blood Prince ",
          "index": 69,
          "level": 2,
          "seq": 15,
          "label": "Harry Potter and the Half-Blood Prince ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "301956980",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.The Twilight Saga: Eclipse ",
          "index": 70,
          "level": 2,
          "seq": 16,
          "label": "The Twilight Saga: Eclipse ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "300523113",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.The Twilight Saga: New Moon ",
          "index": 71,
          "level": 2,
          "seq": 17,
          "label": "The Twilight Saga: New Moon ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "296623634",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.Up ",
          "index": 72,
          "level": 2,
          "seq": 18,
          "label": "Up ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "292979556",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.The Twilight Saga: Breaking Dawn - Part 2",
          "index": 73,
          "level": 2,
          "seq": 19,
          "label": "The Twilight Saga: Breaking Dawn - Part 2",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "292298923",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.Harry Potter and the Order of the Phoenix ",
          "index": 74,
          "level": 2,
          "seq": 20,
          "label": "Harry Potter and the Order of the Phoenix ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "292000866",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.The Chronicles of Narnia: The Lion, the Witch and the Wardrobe ",
          "index": 75,
          "level": 2,
          "seq": 21,
          "label": "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "291709845",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.Harry Potter and the Goblet of Fire ",
          "index": 76,
          "level": 2,
          "seq": 22,
          "label": "Harry Potter and the Goblet of Fire ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "289994397",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.Monsters, Inc. ",
          "index": 77,
          "level": 2,
          "seq": 23,
          "label": "Monsters, Inc. ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "289907418",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.The Hunger Games: Mockingjay - Part 2",
          "index": 78,
          "level": 2,
          "seq": 24,
          "label": "The Hunger Games: Mockingjay - Part 2",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "281666058",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.Gravity ",
          "index": 79,
          "level": 2,
          "seq": 25,
          "label": "Gravity ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "274084951",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.Monsters University ",
          "index": 80,
          "level": 2,
          "seq": 26,
          "label": "Monsters University ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "268488329",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.Shrek ",
          "index": 81,
          "level": 2,
          "seq": 27,
          "label": "Shrek ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "267652016",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.Harry Potter and the Chamber of Secrets ",
          "index": 82,
          "level": 2,
          "seq": 28,
          "label": "Harry Potter and the Chamber of Secrets ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "261970615",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.Jaws ",
          "index": 83,
          "level": 2,
          "seq": 29,
          "label": "Jaws ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "260000000",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.The Hobbit: The Desolation of Smaug ",
          "index": 84,
          "level": 2,
          "seq": 30,
          "label": "The Hobbit: The Desolation of Smaug ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "258355354",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.The Hobbit: The Battle of the Five Armies ",
          "index": 85,
          "level": 2,
          "seq": 31,
          "label": "The Hobbit: The Battle of the Five Armies ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "255108370",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Adventure.Men in Black ",
          "index": 86,
          "level": 2,
          "seq": 32,
          "label": "Men in Black ",
          "description": "",
          "categoryIndex": 3,
          "categoryLabel": "Adventure",
          "color": "#EE5F13",
          "data": {},
          "value": "250147615",
          "visible": true,
          "children": []
        }
      ]
    },
    {
      "id": "Movies.Family",
      "index": 87,
      "level": 1,
      "seq": 3,
      "label": "Family",
      "description": "",
      "categoryIndex": 0,
      "categoryLabel": "",
      "color": "#0088FF",
      "data": {},
      "visible": true,
      "children": [
        {
          "id": "Movies.Family.E.T. the Extra-Terrestrial ",
          "index": 88,
          "level": 2,
          "seq": 0,
          "label": "E.T. the Extra-Terrestrial ",
          "description": "",
          "categoryIndex": 4,
          "categoryLabel": "Family",
          "color": "#F9B052",
          "data": {},
          "value": "434949459",
          "visible": true,
          "children": []
        }
      ]
    },
    {
      "id": "Movies.Animation",
      "index": 89,
      "level": 1,
      "seq": 4,
      "label": "Animation",
      "description": "",
      "categoryIndex": 0,
      "categoryLabel": "",
      "color": "#0088FF",
      "data": {},
      "visible": true,
      "children": [
        {
          "id": "Movies.Animation.Despicable Me 2",
          "index": 90,
          "level": 2,
          "seq": 0,
          "label": "Despicable Me 2",
          "description": "",
          "categoryIndex": 5,
          "categoryLabel": "Animation",
          "color": "#D4785A",
          "data": {},
          "value": "368049635",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Animation.The Secret Life of Pets ",
          "index": 91,
          "level": 2,
          "seq": 1,
          "label": "The Secret Life of Pets ",
          "description": "",
          "categoryIndex": 5,
          "categoryLabel": "Animation",
          "color": "#D4785A",
          "data": {},
          "value": "323505540",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Animation.Despicable Me ",
          "index": 92,
          "level": 2,
          "seq": 2,
          "label": "Despicable Me ",
          "description": "",
          "categoryIndex": 5,
          "categoryLabel": "Animation",
          "color": "#D4785A",
          "data": {},
          "value": "251501645",
          "visible": true,
          "children": []
        }
      ]
    },
    {
      "id": "Movies.Comedy",
      "index": 93,
      "level": 1,
      "seq": 5,
      "label": "Comedy",
      "description": "",
      "categoryIndex": 0,
      "categoryLabel": "",
      "color": "#0088FF",
      "data": {},
      "visible": true,
      "children": [
        {
          "id": "Movies.Comedy.Forrest Gump ",
          "index": 94,
          "level": 2,
          "seq": 0,
          "label": "Forrest Gump ",
          "description": "",
          "categoryIndex": 6,
          "categoryLabel": "Comedy",
          "color": "#42C724",
          "data": {},
          "value": "329691196",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Comedy.Home Alone ",
          "index": 95,
          "level": 2,
          "seq": 1,
          "label": "Home Alone ",
          "description": "",
          "categoryIndex": 6,
          "categoryLabel": "Comedy",
          "color": "#42C724",
          "data": {},
          "value": "285761243",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Comedy.Meet the Fockers ",
          "index": 96,
          "level": 2,
          "seq": 2,
          "label": "Meet the Fockers ",
          "description": "",
          "categoryIndex": 6,
          "categoryLabel": "Comedy",
          "color": "#42C724",
          "data": {},
          "value": "279167575",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Comedy.The Hangover ",
          "index": 97,
          "level": 2,
          "seq": 3,
          "label": "The Hangover ",
          "description": "",
          "categoryIndex": 6,
          "categoryLabel": "Comedy",
          "color": "#42C724",
          "data": {},
          "value": "277313371",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Comedy.How the Grinch Stole Christmas ",
          "index": 98,
          "level": 2,
          "seq": 4,
          "label": "How the Grinch Stole Christmas ",
          "description": "",
          "categoryIndex": 6,
          "categoryLabel": "Comedy",
          "color": "#42C724",
          "data": {},
          "value": "260031035",
          "visible": true,
          "children": []
        },
        {
          "id": "Movies.Comedy.The Hangover Part II ",
          "index": 99,
          "level": 2,
          "seq": 5,
          "label": "The Hangover Part II ",
          "description": "",
          "categoryIndex": 6,
          "categoryLabel": "Comedy",
          "color": "#42C724",
          "data": {},
          "value": "254455986",
          "visible": true,
          "children": []
        }
      ]
    },
    {
      "id": "Movies.Biography",
      "index": 100,
      "level": 1,
      "seq": 6,
      "label": "Biography",
      "description": "",
      "categoryIndex": 0,
      "categoryLabel": "",
      "color": "#0088FF",
      "data": {},
      "visible": true,
      "children": [
        {
          "id": "Movies.Biography.The Blind Side ",
          "index": 101,
          "level": 2,
          "seq": 0,
          "label": "The Blind Side ",
          "description": "",
          "categoryIndex": 7,
          "categoryLabel": "Biography",
          "color": "#FF4B4B",
          "data": {},
          "value": "255950375",
          "visible": true,
          "children": []
        }
      ]
    }
  ]
}

const fs = require('node:fs')
const path = require('node:path')

function toRawData (treeData) {
  function flattenTree (node, parentId = undefined) {
    const current = {
      id: node.id,
      name: node.label,
      value: Number(node.value),
      parent: parentId,
      category: node.categoryLabel
    }

    const children = node.children?.flatMap(child => flattenTree(child, node.id)) ?? []
    return [current, ...children]
  }

  return flattenTree(treeData)
}

if (require.main === module) {
  const rawData = toRawData(treeData)
  const json = JSON.stringify(rawData, null, 2)
  const outputPath = process.argv[2]

  if (outputPath) {
    const resolvedOutputPath = path.resolve(process.cwd(), outputPath)
    fs.writeFileSync(resolvedOutputPath, json + '\n', 'utf8')
    console.log(`JSON written to ${resolvedOutputPath}`)
  } else {
    process.stdout.write(json + '\n')
  }
}

module.exports = {
  toRawData,
  treeData
}

